### ISSUE TITLE
Not added .gitignore

### ISSUE THREAD

**Issue by masuhara** [honami725/Original#2]

**Comment by honami725** [comment]
まっすーさんありがとうございます。これ入れるとどうなるんですか、、？

**Comment by masuhara** [comment]
.gitignoreファイルは、Git管理したくないファイルをignore(無視)することができるよ！

Macでは、ファイルを移動したり操作すると、.DS_Storeという情報ファイルが自動生成されて、それがアプリファイル内にも作られてしまう。

.DS_StoreもGit管理する必要はないのと、.DS_Storeのような不要ファイルがGit管理されていた場合、チーム開発のときに他の人が同じファイルを操作するときに困る(コンフリクトする)ことがあるので、初回コミット時に.gitignoreファイルを入れるクセを今のうちにつけておこう！

.gitignoreの作り方は、GitHubでレポジトリを作るときに同時に生成することもできるし、または下記のようなサービスを使うのも有りだよ。

[gitignore.io](https://www.gitignore.io/)

[gibo](http://qiita.com/tmknom/items/c4bcebe17d25381fa45d)

俺はgiboを使って.gitignoreを生成してるよ！最初は難しいと思うのでそんなに気にすることはないけど、ちょっとずつ美しいプロジェクトファイルを作っていこう！

**Comment by honami725** [comment]
そうなんですね、全く知らなかったので驚きです！
丁寧にありがとうございます！！
これから気をつけます！

**Comment by masuhara** [comment]
[![LGTM](http://lgtm.in/p/Sb8bqD2mq)](http://lgtm.in/i/Sb8bqD2mq)
