### ISSUE TITLE
Back Segue in Storyboard

### ISSUE THREAD

**Issue by masuhara** [honami725/Original#4]
## StoryboardのSegue(セグエ)

画面遷移(がめんせんい)するときにStoryboard上でViewControllerとViewControllerをつなぐ矢印のことをSegue(セグエ)というよ。

Segueには基本的には以下の3種類があるよ。

| 種類 | 意味 | 備考 |
| --- | --- | --- |
| Modal(モーダル) | 現在の画面から"新しい"画面を立ち上げる | 戻るときはdismissViewController。利用規約など、1画面完結型のビューの表示に向いている |
| Push(プッシュ) | 現在の画面から"次の"画面に遷移する | 戻るときはpopViewController。0番目のViewControllerにUINavigationControllerをEmbed inして使う。 |
| Custom(カスタム) | 自作Segue | コードでSegueを定義したいときに使う。 |

画面遷移は、**Modal**と**Push**を頻繁に使うよ。

Segueは基本的には一方通行に設定するよ。理由は2点。
①Segueは画面Aから画面Bにつなぐと、画面Bを新しく生成することになるのでメモリが食われる
②アニメーションが新規ページを開くアニメーションになってしまうので、UXが悪い

実際にSegueで戻るSegueを繋いだときと、戻るアクションをコードで書いたときの違いを比較してみよう！特に②に気づくはず。

正しいSegueで、美しいStoryboardを保とう！！

<img width="840" alt="segue" src="https://cloud.githubusercontent.com/assets/1835427/13151310/f95031c4-d6ac-11e5-845d-dc15e0f1bf56.png">

**Comment by honami725** [comment]
本当にありがとうございます泣
そうなんですね、、
コードで書いてみます！！

**Comment by masuhara** [comment]
[![LGTM](http://lgtm.in/p/cKMxI2EHn)](http://lgtm.in/i/cKMxI2EHn)
